FORMAT: 1A
HOST: https://microclimates.com

# Climate Conrol API

The Microclimates Climate Control API allows developers to interact with Microclimates sites
and devices from the context of a user.

It offers all functionality used in the Microclimates UI, and additional
items for posting and retrieving device data.

# Authorization

All API interactions must be authorized by passing
the user authentication token in the HTTP Authorization header.
```
Authorization: Bearer {token}
```
This token is available in the User Settings section within the Microclimates 
application.

# Security

The API processes only HTTPS requests to `https://microclimates.com/api/v2`, securing the content from
observation while traveling over the network. 

The resource ID and request parameters may be part of the URL, but all resource
data is passed in the request/response body, as to not get logged during server request logging. 

If you feel your API token has been compromised, the  token can be revoked and replaced
with a new token from within the Microclimates application.

# HTTP Requests

The following sections of the HTTP request are handled the same for each API interaction.

## Request URL

The request URL is made with the following parts, in order

Scheme: `https://`  
Server: `microclimates.com`  
API Path: `/api/v2`  
Resource Type: `/{resource type}`  
Resource ID: `/{resource id}` (not used for `POST`)  
Query Parameters: `?param1=value1&param2=value2` (specialized for queries)

## Request Headers

The following request headers are recognized

`Authorization` - (see Authorization section above)  
`Content-Type` - Describes the format of the content body one of `application/json` or `application/x-www-form-urlencoded`  

## Content Body

The format of data supplied in the request body is based on the `Content-Type` header
 (see above).

**Example: applicaton/json**
```
{
    "id": "some-resource-id",
    "name":"Resource Name",
    ...
}
```

JSON data may be, but is not required to be pretty printed as in the above example.

**Example: application/x-www-form-urlencoded**
```
id=some-resource-id&name=Resource%20Name
```

# HTTP Responses

## Status Codes

**The following codes indicate success:**

`200 - OK` Everything went according to plan, and the results are as documented.  
`304 - Not Modified` No body returned. Used in conjunction with the ETag header (above)  

**The following codes indicate an error.** They return an error body vs. the documented body, for the following reasons

`400 - Bad Request` The request fails a precondition and was rejected. Reason indicated in the body.  
`401 - Unauthorized` Authorization header not supplied, or supplied with an invalid token.  
`404 - Not Found` The resource requested by ID is not found in the system.  
`500 - Internal Server Error` Oh crap - something bad happened on our end. You might find something useful in the response body.  
`501 - Not Implemented` Coming soon to an API near you.  

## Response Headers



## Response Body

On successful API call, the body is as documented. 

On unsuccessful API call (status code 400 or higher), the body contains error information.

# Users [/api/v2/users]
User - An individual that interacts with the system

## Read Users [GET]

This is a standard GET, meaning it returns an array of resources, but there will only be one item
in the array - the user specified by the Authentication token.

+ Response 200 (application/json)
    + Attributes (User)

## Update a User [PUT /{id}]

Updates your user profile. Most attributes can be updated, but not all. The `body` can contain 
a subset of attributes to update, or all attributes.

The resource /{id} must be the ID associated with the Authentication token.

+ Attributes (User)
+ Response 200 (application/json)
    + Attributes (User)

## Delete a User [DELETE /{id}]

**Be really careful with this one.** If you delete yourself, that will be the last API call you're
able to make. You will be removed from all sites, and will have to be re-invited. Your user id and
API keys will be different, even if you're invited with the same email address.

The resource /{id} must be the ID associated with the Authentication token.

+ Response 200 (application/json)

# Data Structures

## User (object)
+ id (string)
    The unique user identifier, used in subsequent PUT or DELETE calls.

+ firstName (string)
    First Name

+ lastName (string)